package pack2;
// Generated 27 mai 2024 10:53:21 by Hibernate Tools 4.3.1


import connect.NewHibernateUtil;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;

/**
 * Emp generated by hbm2java
 */
public class Emp  implements java.io.Serializable {


     private Integer id;
     private Dept dept;
     private String nom;
     private String prenom;
     private Integer salaire;
     private String poste;
     private Date dateDeNaissance;

    public Emp() {
    }

    public Emp(Dept dept, String nom, String prenom, Integer salaire, String poste, Date dateDeNaissance) {
       this.dept = dept;
       this.nom = nom;
       this.prenom = prenom;
       this.salaire = salaire;
       this.poste = poste;
       this.dateDeNaissance = dateDeNaissance;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Dept getDept() {
        return this.dept;
    }
    
    public void setDept(Dept dept) {
        this.dept = dept;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public Integer getSalaire() {
        return this.salaire;
    }
    
    public void setSalaire(Integer salaire) {
        this.salaire = salaire;
    }
    public String getPoste() {
        return this.poste;
    }
    
    public void setPoste(String poste) {
        this.poste = poste;
    }
    public Date getDateDeNaissance() {
        return this.dateDeNaissance;
    }
    
    public void setDateDeNaissance(Date dateDeNaissance) {
        this.dateDeNaissance = dateDeNaissance;
    }
    




}


